### ISSUE TITLE
R Markdown versus bookdown

### ISSUE THREAD

**Issue by zenrabbit** [jules32/rmarkdown-website-tutorial#1]
Context
One repo, one folder, and you have multiple .Rmd files you want to aggregate together as a website with multiple pages (one per Rmd).

option 1. http://rmarkdown.rstudio.com/rmarkdown_websites.html

option 2. https://bookdown.org/yihui/bookdown/html.html #check this link looks like it works well

I think the bookdown package is the winner for simplicity?

**Comment by jules32** [comment]
Hi @cjlortie, 

I've been using both options and I think that bookdown is simpler building-wise -->>> but publishing is trickier. 

- With the websites, you develop/write content in .Rmds on a gh-pages branch -> knit .htmls -> and push and voila, it's online!
- With bookdown, you develop/write content on some (eg master) branch -> knit .htmls -> have to transfers the .html files to the gh-pages branch for publishing. This extra step can be done 
    - option 2A: as [described by Yihui using Travis CI](https://bookdown.org/yihui/bookdown/github.html): for: 
    - option 2B: writing a script (in R/bash/something else) to copy html content from the first branch to the gh-pages branch.
    - option don't do this: in Finder copying files from your first branch somewhere else, switching to the gh-pages branch, pasting and pushing.

Option 2A is obviously cleaner and better, and although I've worked hackily (new word there) with Travis CI in the past, in 2 days I couldn't get this to work properly (I was so close but had to move on). Ultimately I opted for option 2B, making this [_deploy.r](https://github.com/OHI-Science/toolbox-training/blob/master/_deploy.r) script (borrowed from a script from Ben Best).
